export const GETPRODUCT = 'GETPRODUCT'
export const GETPRODUCT_SUCCESS = 'GETPRODUCT_SUCCESS'
export const GETPRODUCT_ERROR = 'GETPRODUCT_SUCCESS_ERROR'
export const GETPRODUCT_INITIATED = 'GETPRODUCT_SUCCESS_INITIATED'
